import { ThemeConfig, ThemeId } from '../types';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  rose: {
    id: 'rose',
    name: 'Frosted Rose',
    gradientBg: 'bg-gradient-to-tr from-[#ff9a9e] via-[#fad0c4] to-[#fbc2eb]',
    orb1: 'bg-purple-400/30',
    orb2: 'bg-blue-400/20',
    orb3: 'bg-yellow-300/25',
    cardBg: 'bg-white/20 backdrop-blur-xl',
    cardBorder: 'border-white/30',
    textColor: 'text-white',
    textSecondary: 'text-white/80',
    accentColor: 'text-rose-500',
    buttonBg: 'bg-white/30 hover:bg-white/40 backdrop-blur-md',
    buttonText: 'text-white',
  },
  purple: {
    id: 'purple',
    name: 'Enchanted Lavender',
    gradientBg: 'bg-gradient-to-tr from-[#7f7fd5] via-[#86a8e7] to-[#91eae4]',
    orb1: 'bg-pink-400/30',
    orb2: 'bg-purple-500/30',
    orb3: 'bg-indigo-300/30',
    cardBg: 'bg-white/20 backdrop-blur-xl',
    cardBorder: 'border-white/30',
    textColor: 'text-white',
    textSecondary: 'text-white/80',
    accentColor: 'text-purple-600',
    buttonBg: 'bg-white/30 hover:bg-white/40 backdrop-blur-md',
    buttonText: 'text-white',
  },
  midnight: {
    id: 'midnight',
    name: 'Dark Mystery',
    gradientBg: 'bg-gradient-to-tr from-[#05070e] via-[#0a0f1d] to-[#121829]',
    orb1: 'bg-purple-900/20',
    orb2: 'bg-blue-900/20',
    orb3: 'bg-slate-800/20',
    cardBg: 'bg-slate-900/70 backdrop-blur-2xl',
    cardBorder: 'border-slate-800/80',
    textColor: 'text-white',
    textSecondary: 'text-slate-400',
    accentColor: 'text-emerald-400',
    buttonBg: 'bg-slate-800/80 hover:bg-slate-700/80 backdrop-blur-md',
    buttonText: 'text-white',
  },
  emerald: {
    id: 'emerald',
    name: 'Hijau Emerald',
    gradientBg: 'bg-gradient-to-tr from-[#044e32] via-[#059669] to-[#10b981]',
    orb1: 'bg-emerald-400/30',
    orb2: 'bg-teal-300/20',
    orb3: 'bg-green-300/20',
    cardBg: 'bg-white/20 backdrop-blur-xl',
    cardBorder: 'border-white/30',
    textColor: 'text-white',
    textSecondary: 'text-emerald-100/90',
    accentColor: 'text-emerald-300',
    buttonBg: 'bg-white/25 hover:bg-white/35 backdrop-blur-md',
    buttonText: 'text-white',
  },
  amber: {
    id: 'amber',
    name: 'Golden Glow',
    gradientBg: 'bg-gradient-to-tr from-[#ffecd2] via-[#fcb69f] to-[#ff9a9e]',
    orb1: 'bg-amber-300/40',
    orb2: 'bg-rose-400/30',
    orb3: 'bg-orange-300/30',
    cardBg: 'bg-white/25 backdrop-blur-xl',
    cardBorder: 'border-white/40',
    textColor: 'text-amber-950',
    textSecondary: 'text-amber-900/80',
    accentColor: 'text-rose-600',
    buttonBg: 'bg-white/40 hover:bg-white/50 backdrop-blur-md',
    buttonText: 'text-amber-950',
  },
};
